### ISSUE TITLE
[Bug]: The null pointer exception caused by the tick method of ItemEntity when picking up items.

### ISSUE THREAD

**Issue by clok-1201** [Minestom/Minestom#2914]
### Affected Version

2025.07.11-1.21.7

### Describe the bug

<img width="1919" height="711" alt="Image" src="https://github.com/user-attachments/assets/4ff45267-c2cb-4327-8073-41a6521c7a51" />

### Steps to reproduce the bug

Creating a SchedulerTask to generate an ItemStack for each tick, then let the player pick it up, will cause the following error; my dispatcher-threads is set to 3.

### Code sample

```java
        System.setProperty("minestom.dispatcher-threads", "3")
        val instance = MinecraftServer.getInstanceManager().createInstanceContainer()
        scheduler.scheduleTask({
            val entity = ItemEntity(ItemStack.of(Material.DIAMOND))
            entity.setInstance(instance, Pos(0.0, 0.0, 0.0))
        }, TaskSchedule.nextTick(), TaskSchedule.tick(1))
```

**Comment by Nerorrlex911** [comment]
https://pastebin.com/JsWNM01X 
tried this in version 2025.09.13-1.21.8 and get a similar Exception.
It seems like the collision detection between the player and the item entities has a time lag, which causes the player to detect an item entity that has already been merged (removed). As a result, the player cannot retrieve the merged item entity from entriesByEntityId in EntityTrackerImpl.nearbyEntities().
I guess checking if the entity obtained is null before calling Entity.getLastPosition() should fix this issue.

**Comment by SorkoPiko** [comment]
couldn't reproduce with [`197bda3`](https://github.com/Minestom/Minestom/tree/197bda3cdbae6f636d20ee63feceb952536e2b4e), can you confirm this still happens?
